"""The logo for the site's intro (src/components/Intro.astro), split into parts that move.

Writes src/components/IntroMark.astro: the icon, the wordmark and the subline side by side, each part with a
class, coloured by the site's tokens, so it follows the mode. Intro.astro holds the motion. Run by export.py.
"""
import re
from pathlib import Path

import marks
from marks import n

ROOT = Path(__file__).resolve().parents[3]
OUT = ROOT / "src" / "components" / "IntroMark.astro"


def markup():
    s, before, after = marks.FIT
    (x0, y0), (x1, y1), (x2, y2), (x3, y3) = marks.STRIP
    holes = marks.reel(*marks.HOLES[:2]) + [(32, marks.CY, marks.HOLES[2])]
    cy = n(marks.CY)
    icon = (
        # The strip unrolls through a mask: a stroke along its centre line, drawn from the neck outwards.
        '<mask id="afig-intro-unroll" maskUnits="userSpaceOnUse" x="-10" y="-20" width="90" height="50">'
        f'<path class="unroll" d="M{x0} {y0} C{x1} {y1} {x2} {y2} {x3} {y3}" pathLength="1" stroke="#fff" stroke-width="9" fill="none"/></mask>'
        f'<g transform="translate(32 {n(after)}) scale({s}) translate(-32 {n(before)})">'
        f'<path class="strip" d="{marks.strip_path()}" fill-rule="evenodd" mask="url(#afig-intro-unroll)"/>'
        f'<path class="skin" d="{marks.FIG64}"/>'
        f'<circle class="ring" cx="32" cy="{cy}" r="{n(marks.RING_R)}"/>'
        f'<circle class="flesh" cx="32" cy="{cy}" r="{n(marks.FLESH_R)}"/>'
        # The invisible circle centres the group on the reel, so it turns about the reel's centre.
        f'<g class="holes"><circle cx="32" cy="{cy}" r="{n(marks.RING_R)}" fill="none"/>'
        + "".join(f'<circle cx="{n(x)}" cy="{n(y)}" r="{n(r)}"/>' for x, y, r in holes) + "</g></g>")

    mark = marks.wordmark("light")
    letters, stalk, dot = re.findall(r"<path [^>]*/>", mark.body)
    letters = re.sub(r' fill="[^"]+"', ' class="letters"', letters)
    stalk = re.sub(r' stroke="[^"]+"', ' class="dot-stalk"', stalk)
    dot = re.sub(r' fill="[^"]+"', ' class="dot-fig"', dot)
    sub = marks.text(marks.NAME, 13, "x")
    sub_body = sub.body.replace(' fill="x"', ' class="subline"')

    k, gap = 1.55, 22                     # the icon at 1.55 × its 64-unit box, then a gap
    tx = 64 * k + gap
    ty = (64 * k - (mark.h + 24)) / 2
    w, h = tx + max(mark.w, sub.w) + 4, 64 * k
    return (f'<svg class="afig-intro-mark" viewBox="-6 -6 {n(w + 12)} {n(h + 12)}" aria-hidden="true">'
            f'<g transform="scale({k})">{icon}</g>'
            f'<clipPath id="afig-intro-wipe"><rect class="wipe" x="0" y="-10" width="{n(mark.w)}" height="{n(mark.h + 20)}"/></clipPath>'
            f'<g transform="translate({n(tx)} {n(ty)})"><g clip-path="url(#afig-intro-wipe)">{letters}</g>'
            f'<g class="dot">{stalk}{dot}</g></g>'
            f'<g transform="translate({n(tx + 1)} {n(ty + mark.h + 20)})"><g class="sub">{sub_body}</g></g></svg>')


def write():
    OUT.write_text(
        "---\n// Generated by docs/brand/tools/intro.py from the logo's geometry in marks.py. Don't edit by hand:\n"
        "// change marks.py, then run python docs/brand/tools/export.py. The motion is in Intro.astro.\n---\n\n"
        + markup() + "\n", encoding="utf-8", newline="\n")
    print(OUT.relative_to(ROOT).as_posix())


if __name__ == "__main__":
    write()
